runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  operating_system: ubuntu22
  runtime_version: "3.11.7"


manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20
